#!/bin/bash

### ToDo add go and ruby paths

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
  PATH="$HOME/.local/bin:$PATH"
fi

# Proper locale
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export LC_ALL=en_US.UTF-8

# don't export term
TERM=xterm-256color
export EDITOR=micro

# for Ranger's pager to show colors in preview
export PAGER="less"
export LESS=-r

###

source $HOME/.dotfiles/bash/bash_aliases
source $HOME/.dotfiles/bash/bash_functions

### prompt ###
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}

# zsh
COLOR_DEF=$'%f'
COLOR_USR=$'%F{243}'
COLOR_DIR=$'%F{197}'
COLOR_GIT=$'%F{39}'
setopt PROMPT_SUBST
# export PROMPT='${COLOR_USR}%n ${COLOR_DIR}%~ ${COLOR_GIT}$(parse_git_branch)${COLOR_DEF} $ '
export PROMPT='${COLOR_DIR}%~ ${COLOR_GIT}$(parse_git_branch)${COLOR_DEF} $ '

# bash
# PROMPT_DIRTRIM=4
# reset="\[\033[0m\]"
# user_color="\[\033[01;32m\]"
# host_color="\[\033[1;33m\]"
# path_color="\[\033[01;34m\]"
# bold="\[\033[1m\]"
# PS1="${user_color}\u:${reset}${path_color}[\w]${reset}${bold}\$(parse_git_branch)${reset} "
### ###

